2024-09-28 11:10:56.193973+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "drop table if exists [*]user cascade "; attendu "identifier"
Syntax error in SQL statement "drop table if exists [*]user cascade "; expected "identifier"; SQL statement:
drop table if exists user cascade  [42001-224]
2024-09-28 11:10:56.219704+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; attendu "identifier"
Syntax error in SQL statement "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id)) [42001-224]
2024-09-28 11:10:56.220159+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references user [42001-224]
2024-09-28 11:10:56.221159+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references user [42001-224]
2024-09-28 11:10:56.232130+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references user [42001-224]
2024-09-28 11:13:02.109213+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "drop table if exists [*]user cascade "; attendu "identifier"
Syntax error in SQL statement "drop table if exists [*]user cascade "; expected "identifier"; SQL statement:
drop table if exists user cascade  [42001-224]
2024-09-28 11:13:02.124173+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; attendu "identifier"
Syntax error in SQL statement "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id)) [42001-224]
2024-09-28 11:13:02.125170+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references user [42001-224]
2024-09-28 11:13:02.126168+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references user [42001-224]
2024-09-28 11:13:02.136141+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references user [42001-224]
2024-09-28 11:14:36.178496+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; attendu "identifier"
Syntax error in SQL statement "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id)) [42001-224]
2024-09-28 11:14:36.186488+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references user [42001-224]
2024-09-28 11:14:36.191461+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references user [42001-224]
2024-09-28 11:14:36.193456+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references user [42001-224]
2024-09-28 11:15:11.349137+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; attendu "identifier"
Syntax error in SQL statement "create table [*]user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id integer generated by default as identity, email varchar(255), nom_complet varchar(255), primary key (id)) [42001-224]
2024-09-28 11:15:11.356118+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe add constraint FKbc5ao5i9frhqhno1bmwxu5rlq foreign key (responsable_id) references user [42001-224]
2024-09-28 11:15:11.364960+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists equipe_users add constraint FKpum2ip18hvwj0orpqkngxf5el foreign key (users_id) references user [42001-224]
2024-09-28 11:15:11.366948+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; attendu "identifier"
Syntax error in SQL statement "alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists tache add constraint FKiwf2rjd64no70ggrx8qkxkiip foreign key (user_id) references user [42001-224]
2024-10-04 17:31:37.184382+01:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS"
Syntax error in SQL statement "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS"; SQL statement:
SELECT * FROM UTILISATEUR EQUIPE EQUIPE_USERS [42000-224]
2024-10-04 17:31:39.788952+01:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS EQUIPE"
Syntax error in SQL statement "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS EQUIPE"; SQL statement:
SELECT * FROM UTILISATEUR EQUIPE EQUIPE_USERS EQUIPE [42000-224]
2024-10-04 17:31:45.427853+01:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Erreur de syntaxe dans l'instruction SQL "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE"
Syntax error in SQL statement "SELECT * FROM UTILISATEUR EQUIPE [*]EQUIPE_USERS EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE"; SQL statement:
SELECT * FROM UTILISATEUR EQUIPE EQUIPE_USERS EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE EQUIPE [42000-224]
2024-10-12 10:47:35.755552+01:00 jdbc[37]: null
org.h2.message.DbException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:218)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:135)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2024-10-12 10:47:35.780539+01:00 jdbc[37]: null
org.h2.message.DbException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:218)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:135)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2024-10-12 10:47:35.785517+01:00 jdbc[37]: null
org.h2.message.DbException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:218)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:135)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La connexion n'a pas été fermée et a été récupérée par le ramasse miette.
The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
